# Generated by Django 4.1.4 on 2023-02-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackjack', '0010_guesttable_rename_usergameprofile_usertable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ShockingImplement', max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('PL', 'Player'), ('DL', 'Dealer')], max_length=2)),
                ('name', models.CharField(max_length=48)),
                ('hand', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='GuestTable',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
        migrations.AddField(
            model_name='player',
            name='tables',
            field=models.ManyToManyField(to='blackjack.table'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='blackjack.table'),
        ),
        migrations.AddField(
            model_name='guest',
            name='tables',
            field=models.ManyToManyField(to='blackjack.table'),
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(fields=('table', 'name', 'profile_type'), name='unique_players'),
        ),
    ]
