# Generated by Django 4.1.4 on 2023-02-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0011_guest_hand_player_table_delete_guesttable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='EquableMaintenance', max_length=24, unique=True),
        ),
    ]
