# Generated by Django 4.1.4 on 2023-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0012_alter_guest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_played',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='pending_players',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_entry',
            field=models.BooleanField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='EffervescentMouton', max_length=24, unique=True),
        ),
    ]
