# Generated by Django 4.1.4 on 2023-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0013_table_last_played_table_pending_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='CorneredGauntlet', max_length=24, unique=True),
        ),
    ]
