# Generated by Django 4.1.4 on 2023-02-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0014_alter_guest_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='pending_players',
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='ObjectiveReorganisation', max_length=24, unique=True),
        ),
    ]
