# Generated by Django 4.1.4 on 2023-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0017_alter_guest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pending_players',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='StirringStandardisation', max_length=24, unique=True),
        ),
    ]
