# Generated by Django 4.1.4 on 2023-02-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0019_alter_guest_username_alter_table_pending_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='EccentricDoing', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='pending_players',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
