# Generated by Django 4.1.3 on 2022-11-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=24)),
                ('deck', models.JSONField()),
                ('player_hand', models.JSONField()),
                ('dealer_hand', models.JSONField()),
                ('coin', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
