# Generated by Django 4.1.3 on 2022-11-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_user_alter_game_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_name',
            field=models.CharField(max_length=24),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
