# Generated by Django 4.1.3 on 2022-11-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_player_name_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Table',
        ),
    ]
