# Generated by Django 4.1.3 on 2022-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_table_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='coin',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
