# Generated by Django 4.1.3 on 2022-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_table_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='player_name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
