# Generated by Django 4.1.3 on 2022-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_table_id_alter_table_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='player_name',
            field=models.CharField(max_length=24),
        ),
    ]
