# Generated by Django 4.1.3 on 2022-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_table_id_alter_table_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='table',
            name='action',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
