# Generated by Django 4.1.3 on 2022-11-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_table_is_finished_table_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='dealer_hand',
            new_name='game_data',
        ),
        migrations.RemoveField(
            model_name='table',
            name='action',
        ),
        migrations.RemoveField(
            model_name='table',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='table',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='table',
            name='player_hand',
        ),
    ]
