# Generated by Django 4.1.3 on 2022-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_dealer_hand_table_game_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='player_name',
            field=models.CharField(default="('connotation',)(' feathered',)", max_length=24, unique=True),
        ),
    ]
