# Generated by Django 4.1.4 on 2023-02-09 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.JSONField()),
                ('last_played', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.ManyToManyField(to='blackjack.table')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('PL', 'Player'), ('DL', 'Dealer')], max_length=2)),
                ('name', models.CharField(max_length=48)),
                ('hand', models.JSONField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='blackjack.table')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DecentralizedStock', max_length=24, unique=True)),
                ('tables', models.ManyToManyField(to='blackjack.table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(fields=('table', 'name', 'profile_type'), name='unique_players'),
        ),
    ]
