# Generated by Django 4.2 on 2023-05-02 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blackjack', '0001_initial'), ('blackjack', '0002_remove_guest_tables_remove_table_card_back_and_more'), ('blackjack', '0003_alter_guest_name'), ('blackjack', '0004_table_players_alter_guest_name'), ('blackjack', '0005_remove_table_players_alter_guest_name'), ('blackjack', '0006_alter_guest_name'), ('blackjack', '0007_remove_player_amount_remove_player_card_back_and_more'), ('blackjack', '0008_player_bet_player_card_back_player_coins_and_more'), ('blackjack', '0009_remove_player_card_back_alter_guest_name'), ('blackjack', '0010_remove_player_state_alter_guest_name_and_more'), ('blackjack', '0011_alter_guest_name'), ('blackjack', '0012_player_high_score_alter_guest_name'), ('blackjack', '0013_highscores_player_biggest_bet_alter_guest_name'), ('blackjack', '0014_remove_highscores_name_highscores_content_type_and_more'), ('blackjack', '0015_rename_table_highscores_table_id_alter_guest_name'), ('blackjack', '0016_alter_guest_name_alter_highscores_biggest_bet_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.TimeField(auto_now_add=True)),
                ('deck', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='blackjack.table')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blackjack.table')),
                ('bet', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=2000)),
                ('high_score', models.PositiveIntegerField(default=0)),
                ('biggest_bet', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OverratedPelt', max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biggest_bet', models.PositiveBigIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(default=0, limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('table_id', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'table_id')},
            },
        ),
    ]
