# Generated by Django 4.2 on 2023-05-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.TimeField(auto_now_add=True)),
                ('deck', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='blackjack.table')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blackjack.table')),
                ('bet', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=2000)),
                ('high_score', models.PositiveIntegerField(default=0)),
                ('biggest_bet', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HighScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biggest_bet', models.PositiveBigIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('object_id', models.PositiveIntegerField()),
                ('table_id', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'table_id')},
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
    ]
