# Generated by Django 4.1.4 on 2023-02-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24)),
                ('last_played', models.TimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('history', models.JSONField(null=True)),
                ('deck', models.JSONField()),
                ('card_back', models.CharField(choices=[('ABS', 'abstract'), ('CLD', 'abstract_clouds'), ('SCE', 'abstract_clouds'), ('AST', 'astronaut'), ('BL1', 'blue'), ('BL2', 'blue2'), ('CAR', 'cars'), ('CAS', 'castle'), ('FSH', 'fish'), ('FRG', 'frog'), ('RD1', 'red'), ('RD2', 'red2')], default='RD1', max_length=3)),
                ('state', models.CharField(choices=[('PLYR', 'player'), ('DLER', 'Dealer'), ('BET', 'bet')], default='BET', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.ManyToManyField(to='blackjack.table')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('amount', models.PositiveIntegerField(default=2000)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='blackjack.table')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UnsolvedRugby', max_length=24, unique=True)),
                ('tables', models.ManyToManyField(to='blackjack.table')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blackjack.table')),
            ],
        ),
    ]
