# Generated by Django 4.1.4 on 2023-02-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='table',
            name='card_back',
        ),
        migrations.RemoveField(
            model_name='table',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userproxy',
            name='tables',
        ),
        migrations.AddField(
            model_name='player',
            name='card_back',
            field=models.CharField(choices=[('ABS', 'abstract'), ('CLD', 'abstract_clouds'), ('SCE', 'abstract_clouds'), ('AST', 'astronaut'), ('BL1', 'blue'), ('BL2', 'blue2'), ('CAR', 'cars'), ('CAS', 'castle'), ('FSH', 'fish'), ('FRG', 'frog'), ('RD1', 'red'), ('RD2', 'red2')], default='RD1', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(choices=[('PLYR', 'player'), ('DLER', 'Dealer'), ('BET', 'bet')], default='BET', max_length=4),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='TolerantStory', max_length=24, unique=True),
        ),
    ]
