# Generated by Django 6.1 on 2026-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_squash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('score', models.PositiveIntegerField()),
                ('biggest_bet', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='table',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AlterUniqueTogether(
            name='highscores',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='highscores',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='table',
        ),
        migrations.RemoveField(
            model_name='userproxy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='HighScores',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
