# Generated by Django 4.1.4 on 2022-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='guest_username',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='username',
            field=models.CharField(default='KeyAnkle', max_length=24, unique=True),
        ),
    ]
