# Generated by Django 4.1.4 on 2023-02-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_remove_guest_tables_remove_table_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='RowdyEncounter', max_length=24, unique=True),
        ),
    ]
