# Generated by Django 4.1.4 on 2023-02-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_alter_guest_username_alter_table_last_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='ImplosiveCeiling', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_played',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
