# Generated by Django 4.1.4 on 2023-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blackjack', '0003_alter_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='players',
            field=models.ManyToManyField(through='blackjack.Player', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='UnavoidableHorror', max_length=24, unique=True),
        ),
    ]
