# Generated by Django 4.1.4 on 2023-02-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0003_table_name_alter_guest_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='LawlessBlogger', max_length=24, unique=True),
        ),
    ]
