# Generated by Django 4.1.4 on 2023-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0004_table_players_alter_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='players',
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='ScummyOmission', max_length=24, unique=True),
        ),
    ]
