# Generated by Django 4.1.4 on 2023-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0005_remove_table_players_alter_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='SpareHawk', max_length=24, unique=True),
        ),
    ]
