# Generated by Django 4.1.7 on 2023-03-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0006_alter_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card_back',
        ),
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
        migrations.RemoveField(
            model_name='table',
            name='history',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='blackjack.table'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='OveractiveOfficial', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blackjack.table'),
        ),
    ]
