# Generated by Django 4.1.4 on 2023-02-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0006_alter_guest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='amount',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='table',
            name='history',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='UnintelligentExhibit', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='profile_type',
            field=models.CharField(choices=[('PLYR', 'Player'), ('GUES', 'Guest')], max_length=4),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.JSONField()),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blackjack.table')),
            ],
        ),
    ]
