# Generated by Django 4.1.7 on 2023-03-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0007_remove_player_amount_remove_player_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bet',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='card_back',
            field=models.CharField(choices=[('ABS', 'abstract'), ('CLD', 'abstract_clouds'), ('SCE', 'abstract_clouds'), ('AST', 'astronaut'), ('BL1', 'blue'), ('BL2', 'blue2'), ('CAR', 'cars'), ('CAS', 'castle'), ('FSH', 'fish'), ('FRG', 'frog'), ('RD1', 'red'), ('RD2', 'red2')], default='RD1', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(choices=[('PLR', 'player'), ('DLR', 'Dealer'), ('BET', 'bet')], default='BET', max_length=3),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='ThePoll', max_length=24, unique=True),
        ),
    ]
