# Generated by Django 4.1.4 on 2023-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0007_hand_amount_table_history_table_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='card_back',
            field=models.CharField(choices=[('ABS', 'abstract'), ('CLD', 'abstract_clouds'), ('SCE', 'abstract_clouds'), ('AST', 'astronaut'), ('BL1', 'blue'), ('BL2', 'blue2'), ('CAR', 'cars'), ('CAS', 'castle'), ('FSH', 'fish'), ('FRG', 'frog'), ('RD1', 'red'), ('RD2', 'red2')], default='RD1', max_length=3),
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='SpiritedAssassination', max_length=24, unique=True),
        ),
    ]
