# Generated by Django 4.1.4 on 2023-01-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0007_alter_guestprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='username',
            field=models.CharField(default='PeacefulRaccoon', max_length=24, unique=True),
        ),
    ]
