# Generated by Django 4.1.7 on 2023-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0010_remove_player_state_alter_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='PrimaryCuisine', max_length=24, unique=True),
        ),
    ]
