# Generated by Django 4.1.7 on 2023-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0011_alter_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='high_score',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='ElaborateGlacier', max_length=24, unique=True),
        ),
    ]
