# Generated by Django 4.1.7 on 2023-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0012_player_high_score_alter_guest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('biggest_bet', models.PositiveBigIntegerField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='biggest_bet',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='DanceablePassion', max_length=24, unique=True),
        ),
    ]
