# Generated by Django 4.1.7 on 2023-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0014_remove_highscores_name_highscores_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highscores',
            old_name='table',
            new_name='table_id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='PhobicTrombone', max_length=24, unique=True),
        ),
    ]
