# Generated by Django 4.1.7 on 2023-04-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blackjack', '0015_rename_table_highscores_table_id_alter_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='OverratedPelt', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='highscores',
            name='biggest_bet',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='highscores',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='highscores',
            unique_together={('content_type', 'object_id', 'table_id')},
        ),
    ]
