# Generated by Django 4.2 on 2023-05-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blackjack', '0001_squashed_0016_alter_guest_name_alter_highscores_biggest_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(default='StiltedLoad', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='highscores',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('guest', 'userproxy')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='highscores',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='highscores',
            name='table_id',
            field=models.PositiveIntegerField(),
        ),
    ]
